"""
EOD close routine -- runs at 15:00 weekdays.

Fetches account + positions via the Alpaca client, calculates a snapshot,
writes a dated journal entry, and updates memory/portfolio-state.md.

Skips execution if the kill switch is active.
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

load_dotenv(PROJECT_ROOT / ".env")

from paper_trading.alpaca_client import AlpacaClient  # noqa: E402
from paper_trading.kill_switch import is_halted  # noqa: E402

JOURNAL_DIR = PROJECT_ROOT / "journal"
PORTFOLIO_STATE = PROJECT_ROOT / "memory" / "portfolio-state.md"


def format_positions(positions: list[dict]) -> str:
    if not positions:
        return "None."
    def fmt_signed(amount: float) -> str:
        sign = "+" if amount >= 0 else "-"
        return f"{sign}${abs(amount):,.2f}"

    return "\n".join(
        f"- {p['symbol']}: qty={p['qty']:.2f}, value=${p['market_value']:,.2f}, "
        f"unrealized_pl={fmt_signed(p['unrealized_pl'])}"
        for p in positions
    )


def write_journal_entry(
    date_str: str, account: dict, positions: list[dict], journal_dir: Path
) -> Path:
    journal_dir.mkdir(parents=True, exist_ok=True)
    journal_path = journal_dir / f"{date_str}.md"

    # If an entry already exists, append an automated EOD section instead
    # of overwriting manual content.
    automated_section = f"""

---

## Automated EOD Close — {datetime.now(timezone.utc).isoformat()}

**Account equity:** ${account['equity']:,.2f}
**Cash:**          ${account['cash']:,.2f}
**Buying power:**  ${account['buying_power']:,.2f}
**Status:**        {account['status']}

### Positions

{format_positions(positions)}

"""

    if journal_path.exists():
        existing = journal_path.read_text(encoding="utf-8")
        if "Automated EOD Close" in existing:
            # Replace previous automated section
            marker = "\n\n---\n\n## Automated EOD Close"
            prefix = existing.split(marker)[0]
            journal_path.write_text(encoding="utf-8", data=prefix + automated_section)
        else:
            journal_path.write_text(encoding="utf-8", data=existing + automated_section)
    else:
        header = f"""---
date: {date_str}
timezone: America/Montreal
session-type: paper-trading-auto
strategies-touched: [ma-crossover]
---

# Daily Journal — {date_str}

(Auto-generated by EOD close routine. Fill in manual sections below.)

## What I worked on
(fill manually)

## Market snapshot
(fill manually)

## Trades
(review Alpaca activity feed)

## Surprises
(fill manually)

## Open threads for next session
- [ ] (fill manually)
"""
        journal_path.write_text(encoding="utf-8", data=header + automated_section)
    return journal_path


def write_portfolio_state(
    account: dict, positions: list[dict], path: Path
) -> None:
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Portfolio State",
        "",
        f"Last updated: {timestamp}",
        "",
        f"**Equity:**       ${account['equity']:,.2f}",
        f"**Cash:**         ${account['cash']:,.2f}",
        f"**Buying power:** ${account['buying_power']:,.2f}",
        f"**Status:**       {account['status']}",
        "",
        "## Open positions",
        "",
    ]
    if positions:
        lines.extend([
            "| Symbol | Qty | Market Value | Unrealized P&L |",
            "|--------|-----|--------------|----------------|",
        ])
        for p in positions:
            pl = p['unrealized_pl']
            sign = "+" if pl >= 0 else "-"
            pl_str = f"{sign}${abs(pl):,.2f}"
            lines.append(
                f"| {p['symbol']} | {p['qty']:.2f} | "
                f"${p['market_value']:,.2f} | {pl_str} |"
            )
    else:
        lines.append("None.")
    path.write_text(encoding="utf-8", data="\n".join(lines) + "\n")


def main() -> int:
    if is_halted():
        print("HALTED -- kill switch active. Exiting.")
        return 0

    client = AlpacaClient()
    account = client.get_account()
    positions = client.get_positions()

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    journal_path = write_journal_entry(date_str, account, positions, JOURNAL_DIR)
    write_portfolio_state(account, positions, PORTFOLIO_STATE)

    print(f"Equity:    ${account['equity']:,.2f}")
    print(f"Positions: {len(positions)}")
    print(f"Journal:   {journal_path}")
    print(f"State:     {PORTFOLIO_STATE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
